# Generated by Django 5.2.8 on 2025-12-05 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=100)),
                ('residence_country', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('profession', models.CharField(max_length=255)),
                ('revenue', models.IntegerField()),
                ('source_of_income', models.CharField(max_length=100)),
                ('account_purpose', models.CharField(max_length=100)),
                ('account_type', models.CharField(max_length=100)),
                ('id_type', models.CharField(max_length=50)),
                ('id_number', models.CharField(max_length=255)),
                ('reason', models.CharField(default='Suspected fraud', max_length=255)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
